services:
  usuarios_produtos_kotlin:
    build: usuarios.produtos.kotlin
    container_name: usuarios_produtos_kotlin
    ports:
      - "8080:8080"
    depends_on:
      - db-usuario-produto # Garante que o banco de dados seja iniciado antes da aplicação
    networks:
      - app-network

  db-usuario-produto:
    image: postgres:14
    container_name: usuario_produto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usuario_produto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistência de dados
    networks:
      - app-network
    healthcheck: # ve se esta tudo certo com o banco
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "usuario_produto_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local  # Volume persistente para os dados do banco
